# Generated by Django 6.0.6 on 2026-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_location',
            field=models.CharField(default='Main Office', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
