# Generated by Django 6.0.6 on 2026-06-20 13:02

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_car_image_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
